### ISSUE TITLE
update of lock to 10.9.* breaks this addon

### ISSUE THREAD

**Issue by Floby** [seawatts/ember-simple-auth-auth0#30]
It seems that Auth0 played apprentice sorcerer with semver which causes several issues https://github.com/auth0/lock/issues/782 and https://github.com/auth0/lock/issues/791.

As a matter of fact, this addon, which registers `auth0-lock@^10.7.2` as a bower dependency is unable to handle the 10.9 branch whilst still allowing it to be downloaded by bower.

I get the following error when trying to log in
```
Error while processing route: home Cannot read property 'filter' of undefined TypeError: Cannot read property 'filter' of undefined
    at Class.<anonymous> (http://localhost:4200/assets/logimarket.js:2242:53)
    at ComputedPropertyPrototype.get (http://localhost:4200/assets/vendor.js:31219:28)
    at Object.get (http://localhost:4200/assets/vendor.js:36126:19)
    at Class.get (http://localhost:4200/assets/vendor.js:48786:26)
    at Class.<anonymous> (http://localhost:4200/assets/logimarket.js:2237:48)
    at ComputedPropertyPrototype.get (http://localhost:4200/assets/vendor.js:31219:28)
    at get (http://localhost:4200/assets/vendor.js:36126:19)
    at _getPath (http://localhost:4200/assets/vendor.js:36147:13)
    at Object.get (http://localhost:4200/assets/vendor.js:36122:14)
    at Class.get (http://localhost:4200/assets/vendor.js:48786:26)
```

The problem seems to be that the `session.data.authenticated.profile` is only populated by something like
```
{
  "iss": "https://fja-test.eu.auth0.com/",
  "sub": "auth0|580f66c113660ba533eb5e39",
  "aud": "ilpPFPgH4RVtWgyNWlCXVgSHOVSMEjN6",
  "exp": 1484277544,
  "iat": 1484241544
}
```

As you can see all the userinfo / tokeninfo are missing. This is only the fields that are given in the idToken.

**Comment by Floby** [comment]
Identified the failing part.

in this file https://github.com/seawatts/ember-simple-auth-auth0/blob/develop/addon/utils/create-session-data-object.js#L5

```javascript
export default function createSessionDataObject(profile, tokenInfo) {
  return assign({ profile }, tokenInfo);
}
```

with a 10.9 version of auth0-lock.js, the tokenInfo already has a `profile` field which contains the decoded idToken (instead of storing it in `idTokenPayload`). the way `assign()` works make the "profile" field of tokenInfo to override the one we just got.
I have not found how or when or why they changed that in a minor version.

We probably can change this one line to 

```javascript
export default function createSessionDataObject(profile, tokenInfo) {
  return assign({}, tokenInfo, { profile });
}
```

**Comment by seawatts** [comment]
Great find! Thanks for the PR. Will close after merge
